name: build image

on:
  push:
    branches:
      - "main"
    paths:
      - 'docker/**'
      - 'website/**'
  workflow_dispatch:
  
permissions:
  id-token: write # required for requesting the JWT
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      uses: docker/login-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build the Docker image
      run: |
        make build
        make upload
